### ISSUE TITLE
Sheet style not being applied when preview page

### ISSUE THREAD

**Issue by annamisak** [rajaaalsubairi/fly-program#10]
Can someone help me find the problem why the style sheet is not applied during page preview? I am so frustrated. On my desktop it looks good. I can see colours and the nice setup. 

It looks like the base url is not linked properly to the style sheet when the jekyll generates the pages.

I have tried so many things. 

**I have this in default.html**
`<link href="{{site.baseurl}}/css/style.css" rel="stylesheet">`

**and the browser reads this**

> rajaaalsubairi.github.io CANNOT GET http://rajaaalsubairi.github.io/css/style.css 

the **fly-program** folder is not being placed inside the link

@rajaaalsubairi @shaayaanjameel @gord0186 @dingchangxu

**Comment by annamisak** [comment]
The only way I was able to make the style sheet link properly by making changes to the _config.yml file

**from this:**
> permalink: pretty
 baseurl: ""

**to this:**
> markdown: redcarpet
baseurl: /fly-program

Shouldn't I be able to leave the baseurl empty with only the double quotation?

**Comment by rajaaalsubairi** [comment]
github doesn't use red carpet markdown anymore so you can delete that line. and yes it should work with only the empty quotes. I'm not sure why it's not linking but I'll look into it.

**Comment by annamisak** [comment]
I will remove the **`markdown: red carpet `** and replace it with **`permalink: pretty`**

**Comment by rajaaalsubairi** [comment]
fixed!
