### ISSUE TITLE
stylize inside pages

### ISSUE THREAD

**Issue by shaayaanjameel** [rajaaalsubairi/fly-program#64]
the inside pages needed to be styled

**Comment by shaayaanjameel** [comment]
I can't seem to figure out how to get rid of the text decoration, any suggestions? I tried doing subinfo{ li{text-decoration:none} } and it wouldn't work. I also tried adding the text-decoration part to subinfo itself and still there @rajaaalsubairi

**Comment by rajaaalsubairi** [comment]
ill look at it

**Comment by rajaaalsubairi** [comment]
fixed it
