### ISSUE TITLE
inside page billboard

### ISSUE THREAD

**Issue by shaayaanjameel** [rajaaalsubairi/fly-program#66]
the billboards for the inside pages aren't showing up

**Comment by shaayaanjameel** [comment]
fixed the issue! do you guys think I should round the corners of the images to match the shape of the icon or would you guys prefer that I leave it rectangular? p.s. I haven't synced the image yet so you won't be able to see it. @rajaaalsubairi @dingchangxu @gord0186 @annamisak

**Comment by annamisak** [comment]
I think keep it rectangular. That way it's not the same what their new website looks like

**Comment by shaayaanjameel** [comment]
okay sounds good. do you think that I should make it span the whole page or give it a max width?

**Comment by rajaaalsubairi** [comment]
let it span

**Comment by shaayaanjameel** [comment]
done!
