### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by rajaaalsubairi** [rajaaalsubairi/fly-program#79]
The about, who we are and what we do pages should be combined and styled. the line length right now is too long. i suggest using two columns. @shaayaanjameel

**Comment by shaayaanjameel** [comment]
you want me to combine them both into one page?

**Comment by rajaaalsubairi** [comment]
I guess just the about and what we do section into one page and the who we are a separate page.

**Comment by shaayaanjameel** [comment]
sounds good. consider it done!
