### ISSUE TITLE
Our programs pages 

### ISSUE THREAD

**Issue by rajaaalsubairi** [rajaaalsubairi/fly-program#80]
The program section pages can be styled by ding and rudy. I think we should combine the pages together. I'll create the page with all the info together. Rudy can style the law/leadership/mentor section after i combine the pages and ding can work on the careers page. 

@shaayaanjameel @annamisak @gord0186 @dingchangxu

**Comment by shaayaanjameel** [comment]
So I was going to combine the programs pages and use javascript to collapse and open the sections and then from the nav it can smooth scroll to the sections. What do you think? I want to make sure that the headers and content all have similar styling so maybe we can just use the same classes?

**Comment by annamisak** [comment]
I think we can combine multiple pages no problem, just make sure the navigation is updated as well
